// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: sentium/api/v1/resources.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Resources_List_FullMethodName           = "/sentium.api.v1.Resources/List"
	Resources_ListPrincipals_FullMethodName = "/sentium.api.v1.Resources/ListPrincipals"
)

// ResourcesClient is the client API for Resources service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourcesClient interface {
	List(ctx context.Context, in *ResourcesListRequest, opts ...grpc.CallOption) (*ResourcesListResponse, error)
	ListPrincipals(ctx context.Context, in *ResourcesListPrincipalsRequest, opts ...grpc.CallOption) (*ResourcesListPrincipalsResponse, error)
}

type resourcesClient struct {
	cc grpc.ClientConnInterface
}

func NewResourcesClient(cc grpc.ClientConnInterface) ResourcesClient {
	return &resourcesClient{cc}
}

func (c *resourcesClient) List(ctx context.Context, in *ResourcesListRequest, opts ...grpc.CallOption) (*ResourcesListResponse, error) {
	out := new(ResourcesListResponse)
	err := c.cc.Invoke(ctx, Resources_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *resourcesClient) ListPrincipals(ctx context.Context, in *ResourcesListPrincipalsRequest, opts ...grpc.CallOption) (*ResourcesListPrincipalsResponse, error) {
	out := new(ResourcesListPrincipalsResponse)
	err := c.cc.Invoke(ctx, Resources_ListPrincipals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ResourcesServer is the server API for Resources service.
// All implementations must embed UnimplementedResourcesServer
// for forward compatibility
type ResourcesServer interface {
	List(context.Context, *ResourcesListRequest) (*ResourcesListResponse, error)
	ListPrincipals(context.Context, *ResourcesListPrincipalsRequest) (*ResourcesListPrincipalsResponse, error)
	mustEmbedUnimplementedResourcesServer()
}

// UnimplementedResourcesServer must be embedded to have forward compatible implementations.
type UnimplementedResourcesServer struct {
}

func (UnimplementedResourcesServer) List(context.Context, *ResourcesListRequest) (*ResourcesListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedResourcesServer) ListPrincipals(context.Context, *ResourcesListPrincipalsRequest) (*ResourcesListPrincipalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPrincipals not implemented")
}
func (UnimplementedResourcesServer) mustEmbedUnimplementedResourcesServer() {}

// UnsafeResourcesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ResourcesServer will
// result in compilation errors.
type UnsafeResourcesServer interface {
	mustEmbedUnimplementedResourcesServer()
}

func RegisterResourcesServer(s grpc.ServiceRegistrar, srv ResourcesServer) {
	s.RegisterService(&Resources_ServiceDesc, srv)
}

func _Resources_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resources_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcesServer).List(ctx, req.(*ResourcesListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Resources_ListPrincipals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResourcesListPrincipalsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ResourcesServer).ListPrincipals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Resources_ListPrincipals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ResourcesServer).ListPrincipals(ctx, req.(*ResourcesListPrincipalsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Resources_ServiceDesc is the grpc.ServiceDesc for Resources service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Resources_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sentium.api.v1.Resources",
	HandlerType: (*ResourcesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Resources_List_Handler,
		},
		{
			MethodName: "ListPrincipals",
			Handler:    _Resources_ListPrincipals_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sentium/api/v1/resources.proto",
}
