env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:solid/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - solid
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
