// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: proto/ruek/api/v1/principals.proto

package ruekpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Principal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attrs   *structpb.Struct `protobuf:"bytes,2,opt,name=attrs,proto3,oneof" json:"attrs,omitempty"`
	Segment *string          `protobuf:"bytes,3,opt,name=segment,proto3,oneof" json:"segment,omitempty"`
}

func (x *Principal) Reset() {
	*x = Principal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{0}
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Principal) GetAttrs() *structpb.Struct {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *Principal) GetSegment() string {
	if x != nil && x.Segment != nil {
		return *x.Segment
	}
	return ""
}

type PrincipalsCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      *string          `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Attrs   *structpb.Struct `protobuf:"bytes,2,opt,name=attrs,proto3,oneof" json:"attrs,omitempty"`
	Segment *string          `protobuf:"bytes,3,opt,name=segment,proto3,oneof" json:"segment,omitempty"`
}

func (x *PrincipalsCreateRequest) Reset() {
	*x = PrincipalsCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsCreateRequest) ProtoMessage() {}

func (x *PrincipalsCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsCreateRequest.ProtoReflect.Descriptor instead.
func (*PrincipalsCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{1}
}

func (x *PrincipalsCreateRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *PrincipalsCreateRequest) GetAttrs() *structpb.Struct {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *PrincipalsCreateRequest) GetSegment() string {
	if x != nil && x.Segment != nil {
		return *x.Segment
	}
	return ""
}

type PrincipalsCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Principal *Principal `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
}

func (x *PrincipalsCreateResponse) Reset() {
	*x = PrincipalsCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsCreateResponse) ProtoMessage() {}

func (x *PrincipalsCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsCreateResponse.ProtoReflect.Descriptor instead.
func (*PrincipalsCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{2}
}

func (x *PrincipalsCreateResponse) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

type PrincipalsDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PrincipalsDeleteRequest) Reset() {
	*x = PrincipalsDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsDeleteRequest) ProtoMessage() {}

func (x *PrincipalsDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsDeleteRequest.ProtoReflect.Descriptor instead.
func (*PrincipalsDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{3}
}

func (x *PrincipalsDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PrincipalsDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PrincipalsDeleteResponse) Reset() {
	*x = PrincipalsDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsDeleteResponse) ProtoMessage() {}

func (x *PrincipalsDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsDeleteResponse.ProtoReflect.Descriptor instead.
func (*PrincipalsDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{4}
}

type PrincipalsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Segment         *string `protobuf:"bytes,1,opt,name=segment,proto3,oneof" json:"segment,omitempty"`
	PaginationLimit *uint32 `protobuf:"varint,2,opt,name=pagination_limit,json=paginationLimit,proto3,oneof" json:"pagination_limit,omitempty"`
	PaginationToken *string `protobuf:"bytes,3,opt,name=pagination_token,json=paginationToken,proto3,oneof" json:"pagination_token,omitempty"`
}

func (x *PrincipalsListRequest) Reset() {
	*x = PrincipalsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsListRequest) ProtoMessage() {}

func (x *PrincipalsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsListRequest.ProtoReflect.Descriptor instead.
func (*PrincipalsListRequest) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{5}
}

func (x *PrincipalsListRequest) GetSegment() string {
	if x != nil && x.Segment != nil {
		return *x.Segment
	}
	return ""
}

func (x *PrincipalsListRequest) GetPaginationLimit() uint32 {
	if x != nil && x.PaginationLimit != nil {
		return *x.PaginationLimit
	}
	return 0
}

func (x *PrincipalsListRequest) GetPaginationToken() string {
	if x != nil && x.PaginationToken != nil {
		return *x.PaginationToken
	}
	return ""
}

type PrincipalsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Principals      []*Principal `protobuf:"bytes,1,rep,name=principals,proto3" json:"principals,omitempty"`
	PaginationToken *string      `protobuf:"bytes,2,opt,name=pagination_token,json=paginationToken,proto3,oneof" json:"pagination_token,omitempty"`
}

func (x *PrincipalsListResponse) Reset() {
	*x = PrincipalsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsListResponse) ProtoMessage() {}

func (x *PrincipalsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsListResponse.ProtoReflect.Descriptor instead.
func (*PrincipalsListResponse) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{6}
}

func (x *PrincipalsListResponse) GetPrincipals() []*Principal {
	if x != nil {
		return x.Principals
	}
	return nil
}

func (x *PrincipalsListResponse) GetPaginationToken() string {
	if x != nil && x.PaginationToken != nil {
		return *x.PaginationToken
	}
	return ""
}

type PrincipalsRetrieveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *PrincipalsRetrieveRequest) Reset() {
	*x = PrincipalsRetrieveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsRetrieveRequest) ProtoMessage() {}

func (x *PrincipalsRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsRetrieveRequest.ProtoReflect.Descriptor instead.
func (*PrincipalsRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{7}
}

func (x *PrincipalsRetrieveRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PrincipalsRetrieveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Principal *Principal `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
}

func (x *PrincipalsRetrieveResponse) Reset() {
	*x = PrincipalsRetrieveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsRetrieveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsRetrieveResponse) ProtoMessage() {}

func (x *PrincipalsRetrieveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsRetrieveResponse.ProtoReflect.Descriptor instead.
func (*PrincipalsRetrieveResponse) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{8}
}

func (x *PrincipalsRetrieveResponse) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

type PrincipalsUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attrs   *structpb.Struct `protobuf:"bytes,2,opt,name=attrs,proto3,oneof" json:"attrs,omitempty"`
	Segment *string          `protobuf:"bytes,3,opt,name=segment,proto3,oneof" json:"segment,omitempty"`
}

func (x *PrincipalsUpdateRequest) Reset() {
	*x = PrincipalsUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsUpdateRequest) ProtoMessage() {}

func (x *PrincipalsUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsUpdateRequest.ProtoReflect.Descriptor instead.
func (*PrincipalsUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{9}
}

func (x *PrincipalsUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PrincipalsUpdateRequest) GetAttrs() *structpb.Struct {
	if x != nil {
		return x.Attrs
	}
	return nil
}

func (x *PrincipalsUpdateRequest) GetSegment() string {
	if x != nil && x.Segment != nil {
		return *x.Segment
	}
	return ""
}

type PrincipalsUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Principal *Principal `protobuf:"bytes,1,opt,name=principal,proto3" json:"principal,omitempty"`
}

func (x *PrincipalsUpdateResponse) Reset() {
	*x = PrincipalsUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrincipalsUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrincipalsUpdateResponse) ProtoMessage() {}

func (x *PrincipalsUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ruek_api_v1_principals_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrincipalsUpdateResponse.ProtoReflect.Descriptor instead.
func (*PrincipalsUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_ruek_api_v1_principals_proto_rawDescGZIP(), []int{10}
}

func (x *PrincipalsUpdateResponse) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

var File_proto_ruek_api_v1_principals_proto protoreflect.FileDescriptor

var file_proto_ruek_api_v1_principals_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x75, 0x65, 0x6b, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x84, 0x01, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a,
	0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53,
	0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x88, 0x01,
	0x01, 0x12, 0x1d, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x9e, 0x01, 0x0a, 0x17, 0x50, 0x72, 0x69, 0x6e, 0x63,
	0x69, 0x70, 0x61, 0x6c, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x13, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00,
	0x52, 0x02, 0x69, 0x64, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48,
	0x01, 0x52, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x07,
	0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x05, 0x0a, 0x03, 0x5f, 0x69,
	0x64, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x5f,
	0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x50, 0x0a, 0x18, 0x50, 0x72, 0x69, 0x6e, 0x63,
	0x69, 0x70, 0x61, 0x6c, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x52, 0x09,
	0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x22, 0x29, 0x0a, 0x17, 0x50, 0x72, 0x69,
	0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x1a, 0x0a, 0x18, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61,
	0x6c, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0xcc, 0x01, 0x0a, 0x15, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x07, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x73,
	0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x10, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x0f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x88, 0x01, 0x01, 0x12, 0x2e, 0x0a, 0x10, 0x70, 0x61, 0x67,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x0f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x65,
	0x67, 0x6d, 0x65, 0x6e, 0x74, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x95, 0x01, 0x0a, 0x16, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x70, 0x72,
	0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69,
	0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x52, 0x0a, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61,
	0x6c, 0x73, 0x12, 0x2e, 0x0a, 0x10, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0f,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x88,
	0x01, 0x01, 0x42, 0x13, 0x0a, 0x11, 0x5f, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2b, 0x0a, 0x19, 0x50, 0x72, 0x69, 0x6e, 0x63,
	0x69, 0x70, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x52, 0x0a, 0x1a, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61,
	0x6c, 0x73, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x52, 0x09, 0x70,
	0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x22, 0x92, 0x01, 0x0a, 0x17, 0x50, 0x72, 0x69,
	0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x05, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x48, 0x00, 0x52, 0x05,
	0x61, 0x74, 0x74, 0x72, 0x73, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x07, 0x73, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x07, 0x73, 0x65, 0x67,
	0x6d, 0x65, 0x6e, 0x74, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x73, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x73, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x50, 0x0a,
	0x18, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x72, 0x69,
	0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x72,
	0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63,
	0x69, 0x70, 0x61, 0x6c, 0x52, 0x09, 0x70, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x32,
	0xbf, 0x03, 0x0a, 0x0a, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x12, 0x55,
	0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c,
	0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25,
	0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69,
	0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12,
	0x24, 0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72,
	0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x04,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x22, 0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c,
	0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5b, 0x0a,
	0x08, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x26, 0x2e, 0x72, 0x75, 0x65, 0x6b,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61,
	0x6c, 0x73, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x27, 0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65,
	0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x55, 0x0a, 0x06, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x72, 0x75, 0x65, 0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x73, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x72, 0x75, 0x65,
	0x6b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70,
	0x61, 0x6c, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x75, 0x61, 0x74, 0x75, 0x6b, 0x6f, 0x2f, 0x72, 0x75, 0x65, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x2e, 0x67, 0x65, 0x6e, 0x2f, 0x67, 0x6f, 0x2f, 0x72, 0x75, 0x65, 0x6b, 0x70, 0x62,
	0x3b, 0x72, 0x75, 0x65, 0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_ruek_api_v1_principals_proto_rawDescOnce sync.Once
	file_proto_ruek_api_v1_principals_proto_rawDescData = file_proto_ruek_api_v1_principals_proto_rawDesc
)

func file_proto_ruek_api_v1_principals_proto_rawDescGZIP() []byte {
	file_proto_ruek_api_v1_principals_proto_rawDescOnce.Do(func() {
		file_proto_ruek_api_v1_principals_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_ruek_api_v1_principals_proto_rawDescData)
	})
	return file_proto_ruek_api_v1_principals_proto_rawDescData
}

var file_proto_ruek_api_v1_principals_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_ruek_api_v1_principals_proto_goTypes = []interface{}{
	(*Principal)(nil),                  // 0: ruek.api.v1.Principal
	(*PrincipalsCreateRequest)(nil),    // 1: ruek.api.v1.PrincipalsCreateRequest
	(*PrincipalsCreateResponse)(nil),   // 2: ruek.api.v1.PrincipalsCreateResponse
	(*PrincipalsDeleteRequest)(nil),    // 3: ruek.api.v1.PrincipalsDeleteRequest
	(*PrincipalsDeleteResponse)(nil),   // 4: ruek.api.v1.PrincipalsDeleteResponse
	(*PrincipalsListRequest)(nil),      // 5: ruek.api.v1.PrincipalsListRequest
	(*PrincipalsListResponse)(nil),     // 6: ruek.api.v1.PrincipalsListResponse
	(*PrincipalsRetrieveRequest)(nil),  // 7: ruek.api.v1.PrincipalsRetrieveRequest
	(*PrincipalsRetrieveResponse)(nil), // 8: ruek.api.v1.PrincipalsRetrieveResponse
	(*PrincipalsUpdateRequest)(nil),    // 9: ruek.api.v1.PrincipalsUpdateRequest
	(*PrincipalsUpdateResponse)(nil),   // 10: ruek.api.v1.PrincipalsUpdateResponse
	(*structpb.Struct)(nil),            // 11: google.protobuf.Struct
}
var file_proto_ruek_api_v1_principals_proto_depIdxs = []int32{
	11, // 0: ruek.api.v1.Principal.attrs:type_name -> google.protobuf.Struct
	11, // 1: ruek.api.v1.PrincipalsCreateRequest.attrs:type_name -> google.protobuf.Struct
	0,  // 2: ruek.api.v1.PrincipalsCreateResponse.principal:type_name -> ruek.api.v1.Principal
	0,  // 3: ruek.api.v1.PrincipalsListResponse.principals:type_name -> ruek.api.v1.Principal
	0,  // 4: ruek.api.v1.PrincipalsRetrieveResponse.principal:type_name -> ruek.api.v1.Principal
	11, // 5: ruek.api.v1.PrincipalsUpdateRequest.attrs:type_name -> google.protobuf.Struct
	0,  // 6: ruek.api.v1.PrincipalsUpdateResponse.principal:type_name -> ruek.api.v1.Principal
	1,  // 7: ruek.api.v1.Principals.Create:input_type -> ruek.api.v1.PrincipalsCreateRequest
	3,  // 8: ruek.api.v1.Principals.Delete:input_type -> ruek.api.v1.PrincipalsDeleteRequest
	5,  // 9: ruek.api.v1.Principals.List:input_type -> ruek.api.v1.PrincipalsListRequest
	7,  // 10: ruek.api.v1.Principals.Retrieve:input_type -> ruek.api.v1.PrincipalsRetrieveRequest
	9,  // 11: ruek.api.v1.Principals.Update:input_type -> ruek.api.v1.PrincipalsUpdateRequest
	2,  // 12: ruek.api.v1.Principals.Create:output_type -> ruek.api.v1.PrincipalsCreateResponse
	4,  // 13: ruek.api.v1.Principals.Delete:output_type -> ruek.api.v1.PrincipalsDeleteResponse
	6,  // 14: ruek.api.v1.Principals.List:output_type -> ruek.api.v1.PrincipalsListResponse
	8,  // 15: ruek.api.v1.Principals.Retrieve:output_type -> ruek.api.v1.PrincipalsRetrieveResponse
	10, // 16: ruek.api.v1.Principals.Update:output_type -> ruek.api.v1.PrincipalsUpdateResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_ruek_api_v1_principals_proto_init() }
func file_proto_ruek_api_v1_principals_proto_init() {
	if File_proto_ruek_api_v1_principals_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_ruek_api_v1_principals_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Principal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsRetrieveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsRetrieveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_ruek_api_v1_principals_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrincipalsUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_ruek_api_v1_principals_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_proto_ruek_api_v1_principals_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_proto_ruek_api_v1_principals_proto_msgTypes[5].OneofWrappers = []interface{}{}
	file_proto_ruek_api_v1_principals_proto_msgTypes[6].OneofWrappers = []interface{}{}
	file_proto_ruek_api_v1_principals_proto_msgTypes[9].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_ruek_api_v1_principals_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ruek_api_v1_principals_proto_goTypes,
		DependencyIndexes: file_proto_ruek_api_v1_principals_proto_depIdxs,
		MessageInfos:      file_proto_ruek_api_v1_principals_proto_msgTypes,
	}.Build()
	File_proto_ruek_api_v1_principals_proto = out.File
	file_proto_ruek_api_v1_principals_proto_rawDesc = nil
	file_proto_ruek_api_v1_principals_proto_goTypes = nil
	file_proto_ruek_api_v1_principals_proto_depIdxs = nil
}
